@echo off
setlocal enabledelayedexpansion


title Paket Yükleniyor...
title Yuklenen Paket: requests
echo requests indiriliyor...
pip install requests
cls
title Yuklenen Paket: colorama / Son Yuklenen Paket: requests
echo requests indiriliyor...
echo requests başarıyla indirildi.
echo colorama indiriliyor...
pip install colorama
echo colorama başarıyla indirildi.
cls
title Yuklenen Paket: six / Son Yuklenen Paket: colorama
echo requests indiriliyor...
echo requests başarıyla indirildi.
echo colorama indiriliyor...
echo colorama başarıyla indirildi.
echo six indiriliyor...
pip install six
echo six başarıyla indirildi.
cls
title Yuklenen Paket: urllib3 / Son Yuklenen Paket: six
echo requests indiriliyor...
echo requests başarıyla indirildi.
echo colorama indiriliyor...
echo colorama başarıyla indirildi.
echo six indiriliyor...
echo six başarıyla indirildi.
echo urllib3 indiriliyor...
pip install urllib3
echo urllib3 başarıyla indirildi.
cls
title Yuklenen Paket: futures / Son Yuklenen Paket: urllib3
echo requests indiriliyor...
echo requests başarıyla indirildi.
echo colorama indiriliyor...
echo colorama başarıyla indirildi.
echo six indiriliyor...
echo six başarıyla indirildi.
echo urllib3 indiriliyor...
echo urllib3 başarıyla indirildi.
echo futures indiriliyor...
pip install futures
echo futures başarıyla indirildi.
cls
title Yuklenen Paket: SendSms / Son Yuklenen Paket: futures
echo requests indiriliyor...
echo requests başarıyla indirildi.
echo colorama indiriliyor...
echo colorama başarıyla indirildi.
echo six indiriliyor...
echo six başarıyla indirildi.
echo urllib3 indiriliyor...
echo urllib3 başarıyla indirildi.
echo futures indiriliyor...
echo futures başarıyla indirildi.
echo SendSms indiriliyor...
pip install SendSms
echo SendSms başarıyla indirildi.
cls
title Yuklenen Paket: sms / Son Yuklenen Paket: SendSms
echo requests indiriliyor...
echo requests başarıyla indirildi.
echo colorama indiriliyor...
echo colorama başarıyla indirildi.
echo six indiriliyor...
echo six başarıyla indirildi.
echo urllib3 indiriliyor...
echo urllib3 başarıyla indirildi.
echo futures indiriliyor...
echo futures başarıyla indirildi.
echo SendSms indiriliyor...
echo SendSms başarıyla indirildi.
echo sms indiriliyor...
pip install sms
echo sms başarıyla indirildi.
cls
echo requests indiriliyor...
echo requests başarıyla indirildi.
echo colorama indiriliyor...
echo colorama başarıyla indirildi.
echo six indiriliyor...
echo six başarıyla indirildi.
echo urllib3 indiriliyor...
echo urllib3 başarıyla indirildi.
echo futures indiriliyor...
echo futures başarıyla indirildi.
echo SendSms indiriliyor...
echo SendSms başarıyla indirildi.
echo sms indiriliyor...
echo sms başarıyla indirildi.

title Paket Yükleme Tamamlandı!
title Program başlatılıyor.
cls
echo requests indiriliyor...
echo requests başarıyla indirildi.
echo colorama indiriliyor...
echo colorama başarıyla indirildi.
echo six indiriliyor...
echo six başarıyla indirildi.
echo urllib3 indiriliyor...
echo urllib3 başarıyla indirildi.
echo futures indiriliyor...
echo futures başarıyla indirildi.
echo SendSms indiriliyor...
echo SendSms başarıyla indirildi.
echo sms indiriliyor...
echo sms başarıyla indirildi.
echo ___________________________________
echo Program başlatılıyor.
echo __________________________________
timeout 2
start main.pyw
exit
